package com.br.ioasys.tremquevoa.domain.exceptions

open class UserException : Exception()

class InvalidEmptyFirstNameException : UserException()
class InvalidEmptyLastNameException : UserException()
class InvalidEmptyEmailException : UserException()
class InvalidEmptyPasswordException : UserException()
class InvalidEmptyPasswordConfirmException : UserException()
class InvalidDifferPasswordException : UserException()
class InvalidRegisterException : UserException()
class IvalidLoginException : UserException()
class InvalidEmptyIdException : UserException()
class InvalidEmptyTokenException : UserException()
class InvalidEmptyRefreshTokenException : UserException()
class InvalidUserException : UserException()
class InvalidEmailExecption : UserException()
class InvalidPasswordException : UserException()
class InvalidMinimunPassword : UserException()
class EmailAlreadyUsed : UserException()
class EmptyToken : UserException()
class EmptyCity : UserException()
class EmpytNameContatct : UserException()
class EmpytNumberContatct : UserException()